name: readme
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  event_bus: ^1.1.1
  flustars: ^0.3.3
  html: ^0.14.0+4
  pull_to_refresh: ^1.6.2
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
